# Generated by Django 5.0.6 on 2024-08-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IsBankruptModel',
        ),
    ]
